name: enexus

config:
  components:
    interfaces: false
    ups: true

match:
  logical_operator: OR
  conditions:
    - match_mode: startsWith
      type: SysObjectID
      values:
        - .1.3.6.1.4.1.12148.10
    - type: snmpget
      oid: .1.3.6.1.4.1.12148.10.2.6.0
      match_mode: regex
      values:
        - '(Micropack System|Smartpack S)(\s*)?$'

identify:
  properties:
    vendor:
      - detection: constant
        value: "Eltek"
    model:
      - detection: snmpget
        oid: 1.3.6.1.4.1.12148.10.2.6.0
    serial_number:
      - detection: snmpget
        oid: 1.3.6.1.4.1.12148.10.2.7.0
    os_version:
      - detection: snmpget
        oid: 1.3.6.1.4.1.12148.10.13.8.2.1.8.1
      - detection: snmpget
        oid: 1.3.6.1.4.1.12148.10.13.8.2.1.8.2

components:
  ups:
    battery_voltage:
      - detection: snmpget
        oid: .1.3.6.1.4.1.12148.10.10.5.5.0
        operators:
          - type: modify
            modify_method: multiply
            value: 0.01
    battery_capacity:
      - detection: snmpget
        oid: .1.3.6.1.4.1.12148.10.10.9.5.0
    battery_amperage:
      - detection: snmpget
        oid: .1.3.6.1.4.1.12148.10.10.6.5.0
        operators:
          - type: modify
            modify_method: multiply
            value: 0.1
    battery_temperature:
      - detection: snmpget
        oid: .1.3.6.1.4.1.12148.10.10.7.5.0
    alarm:
      - detection: snmpget
        oid: .1.3.6.1.4.1.12148.10.3.2.5.0
    current_load:
      - detection: snmpget
        oid: .1.3.6.1.4.1.12148.10.9.2.5.0
        operators:
          - type: modify
            modify_method: multiply
            value: 0.1
    mains_voltage_applied:
      - detection: snmpget
        oid: .1.3.6.1.4.1.12148.10.3.2.5.0
        operators:
          - type: switch
            switch_mode: regex
            cases:
              - case: "0"
                operators:
                  - type: modify
                    modify_method: overwrite
                    value: "1"
              - case: ".*"
                operators:
                  - type: modify
                    modify_method: overwrite
                    value: "0"