name: fortigate

config:
  components:
    cpu: true
    memory: true

match:
  conditions:
    - match_mode: startsWith
      type: SysObjectID
      values:
        - .1.3.6.1.4.1.12356.101.1
  logical_operator: OR

identify:
  properties:
    vendor:
      - detection: constant
        value: "Fortinet"
    model:
      - detection: SysObjectID
        operators:
          - type: modify
            modify_method: map
            mappings: sysObjectID.yaml
    serial_number:
      - detection: snmpget
        oid: 1.3.6.1.2.1.47.1.1.1.1.11.1
    os_version:
      - detection: snmpget
        oid: 1.3.6.1.4.1.12356.101.4.1.1.0
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: "^([^,]+),"
            format: "$1"

components:
  cpu:
    load:
      - detection: snmpget
        oid: .1.3.6.1.4.1.12356.101.4.1.3.0
  memory:
    usage:
      - detection: snmpget
        oid: .1.3.6.1.4.1.12356.101.4.1.4.0