name: "powerone"

config:
  components:
    interfaces: false
    ups: true

match:
  logical_operator: "OR"
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.5961.

identify:
  properties:
    vendor:
      - detection: constant
        value: "Power One"