name: ip10

match:
  conditions:
    - match_mode: startsWith
      type: SysObjectID
      values:
        - .1.3.6.1.4.1.2281.1.10
        - .1.3.6.1.4.1.2281.1.7
  logical_operator: OR

identify:
  properties:
    serial_number:
      - detection: snmpget
        oid: ".1.3.6.1.2.1.2.2.1.6.5010"
        use_raw_result: true
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: "(.{2})(.{2})(.{2})(.{2})(.{2})(.{2})"
            format: "$1:$2:$3:$4:$5:$6"
            return_on_mismatch: true