name: ios

config:
  snmp:
    max_repetitions: 1
  components:
    cpu: true
    memory: true
    hardware_health: true

match:
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.9.
    - type: SysDescription
      match_mode: regex
      values:
        - '(?i)^CISCO\s'
  logical_operator: OR

identify:
  properties:
    vendor:
      - detection: constant
        value: "Cisco"
    serial_number:
      - detection: snmpget
        oid: "1.3.6.1.2.1.47.1.1.1.1.11.1"
      - detection: snmpget
        oid: "1.3.6.1.4.1.9.3.6.3.0"
    model:
      - detection: snmpget
        oid: "1.3.6.1.2.1.47.1.1.1.1.13.1"
        operators:
          - type: modify
            modify_method: regexReplace
            replace: ""
            regex: '(?i)^C(ISCO)?'
    model_series:
      - detection: Model
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '^([0-9]+)'
            format: "$1"
    os_version:
      - detection: SysDescription
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'Version ([^, ]+)'
            format: "$1"

components:
  interfaces:
    properties:
      detection: snmpwalk
      values:
        ethernet_like:
          values:
            etherStatsCRCAlignErrors:
              oid: 1.3.6.1.4.1.9.2.2.1.1.12
  hardware_health:
    fans:
      detection: snmpwalk
      values:
        description:
          oid: .1.3.6.1.4.1.9.9.13.1.4.1.2
        state:
          oid: .1.3.6.1.4.1.9.9.13.1.4.1.3
          operators:
            - type: modify
              modify_method: map
              mappings: ios_CiscoEnvMonState.yaml
    power_supply:
      detection: snmpwalk
      values:
        description:
          oid: .1.3.6.1.4.1.9.9.13.1.5.1.2
        state:
          oid: .1.3.6.1.4.1.9.9.13.1.5.1.3
          operators:
            - type: modify
              modify_method: map
              mappings: ios_CiscoEnvMonState.yaml
    voltage:
      detection: snmpwalk
      values:
        description:
          oid: .1.3.6.1.4.1.9.9.13.1.2.1.2
          operators:
            - type: modify
              modify_method: regexReplace
              regex: 'in mV'
              replace: ''
        voltage:
          oid: .1.3.6.1.4.1.9.9.13.1.2.1.3
          operators:
            - type: modify
              modify_method: divide
              precision: 3
              value:
                detection: constant
                value: 1000
        state:
          oid: .1.3.6.1.4.1.9.9.13.1.2.1.7
          operators:
            - type: modify
              modify_method: map
              mappings: ios_CiscoEnvMonState.yaml
    temperature:
      detection: snmpwalk
      values:
        description:
          oid: .1.3.6.1.4.1.9.9.13.1.3.1.2
        temperature:
          oid: .1.3.6.1.4.1.9.9.13.1.3.1.3
        state:
          oid: .1.3.6.1.4.1.9.9.13.1.3.1.6
          operators:
            - type: modify
              modify_method: map
              mappings: ios_CiscoEnvMonState.yaml