name: "linux"

config:
  components:
    memory: true
    disk: true
    server: true

match:
  logical_operator: OR
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - ".1.3.6.1.4.1.8072.3.2.10"
    - type: SysDescription
      match_mode: regex
      values:
        - '^Linux'

components:
  memory:
    properties:
      detection: snmpwalk
      values:
        usage:
          oid: ".1.3.6.1.4.1.2021.4.6.0"
          operators:
            - type: modify
              modify_method: add
              value:
                detection: snmpget
                oid: ".1.3.6.1.4.1.2021.4.14.0"
            - type: modify
              modify_method: add
              value:
                detection: snmpget
                oid: ".1.3.6.1.4.1.2021.4.15.0"
            - type: modify
              modify_method: multiply
              value:
                detection: constant
                value: -100
            - type: modify
              modify_method: divide
              value:
                detection: snmpget
                oid: ".1.3.6.1.4.1.2021.4.5.0"
            - type: modify
              modify_method: add
              value:
                detection: constant
                value: 100
  server:
    procs:
      - detection: snmpget
        oid: ".1.3.6.1.2.1.25.1.6.0"
    users:
      - detection: snmpget
        oid: "1.3.6.1.2.1.25.1.5.0"